version: "3.4"

services:
  rt:
    image: rt:latest
    ports:
      - "5280:5280"
    build: .
    
    restart: always
    networks:
      - web

networks:
  web:
    external:
      name: "${NETWORK_NAME:-web}"
